### ISSUE TITLE
Error en respuesta de payu

### ISSUE THREAD

**Issue by rogmoreno** [saulmoralespa/magento2-payulatam#2]
Hola primero que todo excelente trabajo, te cuento estoy probando el modulo y cuando el cliente regresa de pagar obtiene una página en blanco con un error 500

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getMethod() on null in /home/xxx/public_html/vendor/saulmoralespa/magento2-payulatam/Controller/Payment/Complete.php:104

en las lineas  

$method = $order->getPayment()->getMethod();
$methodInstance = $this->_paymentHelper->getMethodInstance($method);

¿sabes como solucionarlo?

**Comment by saulmoralespa** [comment]
Actualiza de nuevo, ya lo solucione.
